export const demoProjects = [
  { id: 'demo-fashion', mode: 'BRAND' as const, name: 'Nara Standard', brief: 'A fictional outerwear label looking beyond cropped silhouettes.', objective: 'Define the next distinctive editorial campaign territory.', stage: 'OPPORTUNITIES', isDemo: true, evidenceCount: 18 },
  { id: 'demo-artist', mode: 'ARTIST' as const, name: 'Aster Vale', brief: 'A fictional electronic artist shaping the visual world for a debut EP.', objective: 'Build a coherent release world that can scale across cover, film and live visuals.', stage: 'CREATIVE_DEVELOPMENT', isDemo: true, evidenceCount: 14 },
];

const fashionFindings = [
  { id: 'f1', category: 'PRODUCT', classification: 'FACT', finding: 'The fictional brief specifies heavyweight cotton outerwear and full-length proportions.', sourceLabel: 'Founder-supplied demo brief', observedAt: '2026-09-09', confidence: 'HIGH', relevance: 'Defines the product truth the work must preserve.' },
  { id: 'f2', category: 'COMPETITORS', classification: 'OBSERVATION', finding: 'Four fictional comparison sets use tightly cropped silhouettes as the dominant styling device.', sourceLabel: 'Demo comparison set, 4 of 4', observedAt: '2026-09-09', confidence: 'MEDIUM', relevance: 'Shows where the sample clusters. It does not prove a whole-category trend.' },
  { id: 'f3', category: 'AUDIENCE', classification: 'INFERENCE', finding: 'A longer silhouette may read as a deliberate counter-position for buyers tired of interchangeable proportions.', sourceLabel: 'Inference from f1 and f2', observedAt: '2026-09-09', confidence: 'LOW', relevance: 'Useful direction to test with real customer language.' },
  { id: 'f4', category: 'VISUAL', classification: 'SIGNAL', finding: 'Vertical negative space repeats across the strongest saved references.', sourceLabel: 'Demo moodboard, 7 of 10 references', observedAt: '2026-09-09', confidence: 'MEDIUM', relevance: 'Suggests a visual grammar for scale and length.' },
];

const artistFindings = [
  { id: 'a1', category: 'BRAND', classification: 'FACT', finding: 'The user-supplied demo release note centres on distance, repetition and late-night movement.', sourceLabel: 'Fictional release note', observedAt: '2026-09-09', confidence: 'HIGH', relevance: 'The release world should express these themes without invented biography.' },
  { id: 'a2', category: 'VISUAL', classification: 'OBSERVATION', finding: 'Saved references repeatedly frame performers through reflective or translucent material.', sourceLabel: 'Demo reference board, 6 of 9 images', observedAt: '2026-09-09', confidence: 'MEDIUM', relevance: 'A concrete visual behaviour, not a claim about the wider scene.' },
  { id: 'a3', category: 'CULTURE', classification: 'INFERENCE', finding: 'A deliberately partial view of the artist could make distance feel authored rather than anonymous.', sourceLabel: 'Inference from a1 and a2', observedAt: '2026-09-09', confidence: 'LOW', relevance: 'A creative hypothesis to test against artist fit.' },
];

export const demoWorkspaces = {
  'demo-fashion': {
    project: demoProjects[0],
    memory: [
      { field: 'Identity', value: 'Quietly exacting outerwear. Product detail over lifestyle theatre.', confidence: 'MEDIUM', evidence: ['f1'] },
      { field: 'Audience', value: 'UNKNOWN. The demo proposes design-aware buyers, but no real customer evidence exists.', confidence: 'LOW', evidence: [] },
      { field: 'Visual language', value: 'Long vertical frames, direct flash, pale industrial interiors, little decorative styling.', confidence: 'MEDIUM', evidence: ['f4'] },
      { field: 'Constraints', value: 'Do not imply sustainability, provenance or performance claims without client proof.', confidence: 'HIGH', evidence: ['f1'] },
    ],
    findings: fashionFindings,
    competitors: [
      { name: 'North Quarry', position: 'Technical minimalism', visual: 'Grey studio, cropped utility layers', pattern: 'Product grids and close details', difference: 'Nara can own length and spatial scale.', evidence: 'Demo source set only' },
      { name: 'Morrow Unit', position: 'Design-led streetwear', visual: 'Concrete, flash, dense layering', pattern: 'Fast drops and creator portraits', difference: 'Nara can reduce noise and slow the frame down.', evidence: 'Demo source set only' },
      { name: 'Field Assembly', position: 'Functional wardrobe', visual: 'Outdoor neutralism', pattern: 'Fabric proof and travel utility', difference: 'Nara should not borrow outdoor-performance codes.', evidence: 'Demo source set only' },
    ],
    signals: [
      { id: 's1', type: 'COMPETITOR', title: 'The sample clusters around crop', description: 'All four fictional comparison sets use abbreviated proportions as a recognisable silhouette.', evidence: ['f2'], strength: 'MODERATE', confidence: 'MEDIUM', freshness: 'Demo captured 2026-09-09', creativeRelevance: 'A visible point of difference is available.', implication: 'Test length as the organising device.', counterEvidence: 'The sample is small and fictional.' },
      { id: 's2', type: 'VISUAL', title: 'Space can make length legible', description: 'Saved references use tall frames and clear floor-to-ceiling space to exaggerate proportion.', evidence: ['f4'], strength: 'EMERGING', confidence: 'MEDIUM', freshness: 'Demo captured 2026-09-09', creativeRelevance: 'The product difference can be shown without copy.', implication: 'Build images around uninterrupted vertical scale.', counterEvidence: 'No audience response data exists.' },
    ],
    opportunities: [
      { id: 'o1', title: 'Keep the length', oneLine: 'Make refusal to crop the product and the campaign idea.', observed: 'The comparison sample clusters around abbreviated silhouettes while the product brief specifies full length.', whyItMatters: 'A product truth becomes an instantly visible category counterpoint.', audience: 'Design-aware outerwear buyers, still a hypothesis.', tension: 'The market compresses. Nara extends.', evidence: ['f1', 'f2', 'f4'], counterEvidence: 'No live sales or audience data proves crop fatigue.', whyThisProject: 'The idea comes from the actual cut of the hero product.', whyNow: 'Useful as a first real-client question, not a time-sensitive trend claim.', creativePossibility: 'Tall portraits, long copy columns, garments crossing frame boundaries and a physical poster series.', risk: 'Length alone may feel formal unless casting and movement add life.', originality: 8, brandFit: 9, evidenceStrength: 6, feasibility: 8, confidence: 'MEDIUM', recommendation: true, status: 'PENDING' },
      { id: 'o2', title: 'A coat needs a room', oneLine: 'Treat the garment as architecture and give every look a measured volume.', observed: 'Saved references use negative space more consistently than decorative sets.', whyItMatters: 'Space makes material, construction and proportion easier to read.', audience: 'People who value construction over logos.', tension: 'More room, less noise.', evidence: ['f1', 'f4'], counterEvidence: 'The reference collection may reflect curator taste rather than audience preference.', whyThisProject: 'The garment has enough scale to shape the frame.', whyNow: 'Can be produced as editorial, social and retail material without a new product claim.', creativePossibility: 'Measured rooms, floor marks, garment diagrams and portrait diptychs.', risk: 'Can drift into cold architecture imagery.', originality: 7, brandFit: 8, evidenceStrength: 5, feasibility: 7, confidence: 'LOW', recommendation: false, status: 'SAVED' },
      { id: 'o3', title: 'Weather without wilderness', oneLine: 'Show protection in the city without borrowing outdoor-adventure clichés.', observed: 'One comparison brand already owns outdoor utility codes.', whyItMatters: 'Nara can communicate shelter while staying culturally and visually urban.', audience: 'City buyers who want coverage, not expedition cosplay.', tension: 'Protected, not performed.', evidence: ['f1'], counterEvidence: 'Requires live competitor verification before client use.', whyThisProject: 'The outerwear use case is real even when performance claims are not.', whyNow: 'A practical route for autumn content if the release calendar supports it.', creativePossibility: 'Street thresholds, rain seen through glass and indoor-to-outdoor continuity.', risk: 'Do not imply waterproof performance without proof.', originality: 6, brandFit: 8, evidenceStrength: 4, feasibility: 9, confidence: 'LOW', recommendation: false, status: 'PENDING' },
    ],
    development: {
      insight: 'The strongest distinction is already cut into the product.', problem: 'Outerwear imagery in the demo set collapses into the same abbreviated silhouette.', tension: 'The market compresses. Nara extends.', proposition: 'Keep the length.', bigIdea: 'A visual campaign built around everything that refuses to be shortened.', narrative: 'Each execution protects space for the garment. Nothing crops the product for convenience.', line: 'KEEP THE LENGTH', message: 'Full-length outerwear, shown at full scale.', emotionalTarget: 'Assured, spacious and exact. Never precious.', principles: ['Show the full silhouette before detail.', 'Use architecture to measure scale.', 'Movement should reveal weight, not imitate action sport.'], hero: 'A floor-to-ceiling portrait sequence with the subject crossing a red measurement line.', supporting: ['Street poster diptychs', 'Slow vertical social pans', 'Product detail sheets'], risks: ['Coldness', 'Over-formality', 'Accidental performance claims'],
    },
    artDirection: {
      thesis: 'Vertical space is the luxury. The image makes the garment feel long before the viewer reads a word.', emotion: 'Assured, spacious, exact.', colour: 'Paper grey, hard black, concrete and one measured red line.', contrast: 'Direct flash against soft ambient room light.', texture: 'Heavy cotton, sealed concrete, brushed aluminium, uncoated paper.', lighting: 'One frontal flash plus broad cool daylight. Shadows stay visible.', composition: 'Full body, low horizon, uninterrupted floor and ceiling. Detail crops only after the full silhouette.', camera: 'Mostly locked, waist-height, square to the architecture.', people: 'Casting should feel self-possessed, not model-performative.', styling: 'One garment per frame. No layered styling that hides the cut.', location: 'Tall civic or industrial interiors with real material character.', typography: 'Large serif statements and narrow factual captions.', motion: 'Slow vertical reveals, one decisive cut at the hem or threshold.', do: ['Let the garment interrupt the grid.', 'Keep spatial measurements visible.', 'Show weight through small movement.'], dont: ['No alpine cues.', 'No smoke, particles or generic slow motion.', 'No crop that removes the hem.'],
    },
    storyboard: [
      { time: '00:00–00:03', frame: 'Empty vertical room. A red line crosses the wall.', camera: 'Locked wide, waist height', action: 'Subject enters below frame edge', light: 'Cool daylight', location: 'Concrete hall', transition: 'Hard cut in', audio: 'Room tone and one footstep', copy: 'KEEP', purpose: 'Establish scale before product.' },
      { time: '00:03–00:07', frame: 'Full silhouette reaches the measurement line.', camera: 'Slow 10% push', action: 'Garment settles after movement', light: 'Direct frontal flash', location: 'Same hall', transition: 'Match on line', audio: 'Fabric weight, low pulse', copy: 'THE LENGTH', purpose: 'Reveal the product truth.' },
      { time: '00:07–00:12', frame: 'Three material details occupy a strict vertical triptych.', camera: 'Macro, static', action: 'Hand closes cuff once', light: 'Raking side light', location: 'Table set', transition: 'Three hard cuts', audio: 'Closure click', copy: 'NARA STANDARD', purpose: 'Turn scale into construction proof.' },
    ],
    feedback: [{ label: 'Strong visual potential', note: 'The red measurement line gives the system a repeatable device.', decision: 'SAVE' }, { label: 'Needs proof', note: 'Do not use audience fatigue language until real comments support it.', decision: 'COMMENT' }],
  },
  'demo-artist': {
    project: demoProjects[1], memory: [], findings: artistFindings, competitors: [],
    signals: [{ id: 'as1', type: 'VISUAL', title: 'Partial visibility fits the release theme', description: 'Reflection and translucent materials recur in the supplied reference set.', evidence: ['a1', 'a2'], strength: 'EMERGING', confidence: 'MEDIUM', freshness: 'Demo captured 2026-09-09', creativeRelevance: 'The visual device can connect cover, film and live imagery.', implication: 'Test one material system across formats.', counterEvidence: 'Artist approval has not been recorded.' }],
    opportunities: [{ id: 'ao1', title: 'Seen through it', oneLine: 'Build the release world through surfaces that reveal and withhold at once.', observed: 'The written themes and reference behaviour both point to distance.', whyItMatters: 'One physical device can unify the release without inventing lore.', audience: 'Existing and new listeners, no demographic assumptions.', tension: 'Present but never fully available.', evidence: ['a1', 'a2'], counterEvidence: 'No audience response has been gathered.', whyThisProject: 'The device grows from the supplied release themes.', whyNow: 'It can shape cover, teaser and performance capture before production fragments.', creativePossibility: 'Reflective sleeves, translucent stage scrims, partial portrait films and refracted type.', risk: 'Can become generic electronic-music obscurity.', originality: 7, brandFit: 8, evidenceStrength: 6, feasibility: 7, confidence: 'MEDIUM', recommendation: true, status: 'PENDING' }],
    development: {}, artDirection: {}, storyboard: [], feedback: [],
  },
} as const;

export type DemoProjectId = keyof typeof demoWorkspaces;

export function getDemoWorkspace(id: string) {
  return demoWorkspaces[id as DemoProjectId] ?? demoWorkspaces['demo-fashion'];
}
